# Banco de Dados Local
spring.datasource.url=jdbc:postgresql://localhost:5432/carteirajulhina_dev
spring.datasource.username=postgres
spring.datasource.password=sua_senha_local_aqui
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Secret JWT para Dev
api.security.token.secret=festa_julhina_secret_dev_only